### ISSUE TITLE
Draw circles on map

### ISSUE THREAD

**Issue by Arturokin12** [capacitor-community/google-maps#195] opened 2022-08-28 15:27 UTC
**Does this feature exist in the Google Maps SDK for android and iOS? Please link the documentation for this feature.**
[Link to the feature in SDK docs](https://developers.google.com/maps/documentation/android-sdk/reference/com/google/android/libraries/maps/model/Circle)

**Describe the solution you'd like**
A function to draw circles given the coordinates, like this image:

https://stackoverflow.com/questions/39124706/android-google-maps-polygon-add-circle-hole

**Comment by tafelnl** [comment] 2022-09-09 10:17
Closing as duplicate of https://github.com/capacitor-community/google-maps/issues/157

**Closed by tafelnl** 2022-09-09 10:17 UTC
Labels: enhancement
