### ISSUE TITLE
I can´t use shapes, polygon, circles and polyline 

### ISSUE THREAD

**Issue by halie412** [capacitor-community/google-maps#188] opened 2022-07-24 03:39 UTC
**Is your feature request related to a problem? Please describe.**
I´m trying to use this plugin in version with shapes without any success, since many days. 

**Describe the solution you'd like**
What we can do for use an version with shapes, polygon, circles and polyline of this plugin?

**Comment by tafelnl** [comment] 2022-08-21 18:22
Duplicate of https://github.com/capacitor-community/google-maps/issues/157

**Closed by tafelnl** 2022-08-21 18:22 UTC
Labels: enhancement
