### ISSUE TITLE
Question on Gesture Support

### ISSUE THREAD

**Issue by selected-pixel-jameson** [capacitor-community/google-maps#43] opened 2021-04-19 13:02 UTC
Right now it says that gesture support is a WIP. 

What gestures are supported? Can I drag the map? Pinch too Zoom? etc... 

Thanks!

**Comment by hemangsk** [comment] 2021-05-21 07:18
Hi, sorry for responding late. https://github.com/capacitor-community/capacitor-googlemaps-native/blob/master/src/definitions.ts#L97 shows list of all gestures which work

**Comment by tafelnl** [comment] 2021-06-22 12:07
I think this one can be closed as a duplicate of #17

**Comment by tafelnl** [comment] 2022-03-16 15:26
We've just released a (pretty stable) beta for version 2 of this plugin under the name [`@capacitor-community/google-maps`](https://www.npmjs.com/package/@capacitor-community/google-maps).

It features a more complete and consistent API. Also the map can finally be rendered behind the webview in this new version.

Extensive documentation for v2 can be found here: https://capacitor-community.github.io/google-maps/

Since version 1 lacked a lot of (basic) features, did not have good coding practices, had a poor API and it is not recommended to use it anymore, we've dropped support for it. Therefore I will close this issue. We believe version 2 offers a better Developer Experience and is a much better fit for anyones use case.

**Closed by tafelnl** 2022-03-16 15:26 UTC
Labels: question, needs information
